apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: argocd # Deploying in the same namespace as ArgoCD for simplicity
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
