# argocd-apps/nginx-oci-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-oci-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts # <-- CHANGE REGISTRY HERE
    chart: nginx
    targetRevision: 20.0.4 # <-- Ensure version matches
    helm:
      releaseName: nginx-oci-release
      values: |
        replicaCount: 1
        service:
          type: ClusterIP
          ports:
            - port: 80
              targetPort: http
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-oci-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true