# argocd-apps/nginx-helm-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm-app # A new, distinct application name for the Helm deployment
  namespace: argocd   # ArgoCD Application resources are typically in the argocd namespace
spec:
  project: default    # Use the default ArgoCD project
  source:
    repoURL: https://charts.bitnami.com/bitnami # The URL of the Bitnami Helm chart repository
    chart: nginx          # The name of the chart within that repository
    targetRevision: 20.0.3 # Specify a specific, stable chart version. (Current as of May 2025)
    # You can optionally specify values to override in the Helm chart here:
    # helm:
    #   values: |
    #     replicaCount: 2
    #     service:
    #       type: ClusterIP
    #     ingress:
    #       enabled: true
    #       hostname: nginx-helm.example.com
  destination:
    server: https://kubernetes.default.svc # The in-cluster Kubernetes API server
    namespace: nginx-helm-app # Deploy the Nginx Helm chart into its own dedicated namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true # Automatically create the destination namespace if it doesn't exist