image:
  repository: alkon100/hello-world # nginxdemos/hello
  tag: latest
  pullPolicy: Always #IfNotPresent

replicaCount: 2

service:
  type: ClusterIP # also works with Ingress
  port: 80

#ingress:
#  enabled: true
#  className: nginx
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
#  hosts:
#    - host: hello.192-168-65-3.nip.io
#      paths:
#        - path: /
#          pathType: Prefix
