image:
  repository: alkon100/hello-world # Must match DockerHub push
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP # works with Ingress
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: hello.192-168-65-3.nip.io
      paths:
        - path: /
          pathType: Prefix
