# .github/workflows/deploy-argocd-app.yaml
name: Deploy ArgoCD HTTP Ingress and Nginx App

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
    paths:
      - 'argocd-ingress/**'
#       - 'argocd-apps/**'              # This already covers nginx-oci-app.yaml
      - 'argocd-apps/nginx-oci-app.yaml'
      - 'k8s-manifests/nginx/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Apply Modified ArgoCD Ingress (HTTP)
      run: kubectl apply -f argocd-ingress/argocd-ingress-http.yaml --validate=false

#    - name: Apply ArgoCD Nginx Application (Raw YAML)
#      run: kubectl apply -f argocd-apps/nginx-app.yaml --validate=false
#
#    - name: Apply ArgoCD Nginx Helm Application (from Repo)
#      run: kubectl apply -f argocd-apps/nginx-helm-app.yaml --validate=false

    - name: Apply ArgoCD Nginx OCI Helm Application # <--- ADD THIS NEW STEP
      run: kubectl apply -f argocd-apps/nginx-oci-app.yaml --validate=false

#    - name: Verify ArgoCD Raw Nginx Application Status
#      run: |
#        echo "Waiting for ArgoCD application 'nginx-test-app' to become Healthy..."
#        kubectl wait --for=jsonpath='{.status.health.status}'=Healthy application/nginx-test-app -n argocd --timeout=5m
#        echo "ArgoCD application 'nginx-test-app' is Healthy."
#        kubectl get application nginx-test-app -n argocd -o yaml
#
#    - name: Verify ArgoCD Helm Nginx Application Status
#      run: |
#        echo "Waiting for ArgoCD application 'nginx-helm-app' to become Healthy..."
#        kubectl wait --for=jsonpath='{.status.health.status}'=Healthy application/nginx-helm-app -n argocd --timeout=5m
#        echo "ArgoCD application 'nginx-helm-app' is Healthy."
#        kubectl get application nginx-helm-app -n argocd -o yaml

    - name: Verify ArgoCD OCI Helm Nginx Application Status # <--- ADD THIS NEW STEP
      run: |
        echo "Waiting for ArgoCD application 'nginx-oci-app' to become Healthy..."
        kubectl wait --for=jsonpath='{.status.health.status}'=Healthy application/nginx-oci-app -n argocd --timeout=5m
        echo "ArgoCD application 'nginx-oci-app' is Healthy."
        kubectl get application nginx-oci-app -n argocd -o yaml