name: Deploy ArgoCD App (OCI)

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Publish Python App & Helm Chart"]
    types:
      - completed

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Download chart version
        uses: actions/download-artifact@v4
        with:
          name: chart-version

      - name: Read chart version
        id: read_version
        run: echo "CHART_VERSION=$(cat chart-version.txt)" >> $GITHUB_ENV

      - name: Login to Docker Hub (for Helm OCI)
        uses: docker/login-action@v3
        with:
          registry: registry-1.docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Helm Chart from OCI (Docker Hub)
        run: |
          echo "Pulling hello-chart from Docker Hub OCI..."
          helm pull oci://registry-1.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/hello-chart --version $CHART_VERSION
          ls -l

      - name: Deploy and Sync ArgoCD App from YAML
        uses: jc21/argocd-deploy@v1.4.0
        with:
          server: ${{ secrets.ARGOCD_SERVER }}
          token: ${{ secrets.ARGOCD_TOKEN }}
          file: argocd-apps/hello-chart-app.yaml
          insecure: true
          sync: true
          waitSync: true
          waitHealth: true
