name: Deploy ArgoCD App (OCI)

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Publish Python App & Helm Chart"]
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Download Chart Version Artifact
        uses: actions/download-artifact@v4
        with:
          name: chart-version

      - name: Prepare Application Manifest from Template
        run: |
          CHART_VERSION=$(cat chart-version.txt)
          echo "Using chart version: $CHART_VERSION"
          export CHART_VERSION
          export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          envsubst < argocd-apps/hello-chart-app.yaml.template > argocd-apps/hello-chart-app.yaml

      - name: Apply ArgoCD Application
        run: |
          kubectl apply -f argocd-apps/hello-chart-app.yaml

      - name: Login to ArgoCD
        uses: clowdhaus/argo-cd-action@v2
        with:
          version: v2.3.0
          command: login ${{ secrets.ARGOCD_SERVER }} --insecure --grpc-web --auth-token ${{ secrets.ARGOCD_TOKEN }}

      - name: Sync ArgoCD Application
        uses: clowdhaus/argo-cd-action@v2
        with:
          version: v2.3.0
          command: app sync hello-chart-app --grpc-web

      - name: Wait for Application to be Healthy
        uses: clowdhaus/argo-cd-action@v2
        with:
          version: v2.3.0
          command: app wait hello-chart-app --health --operation --timeout 90s --grpc-web
