name: Publish Python App & Helm Chart

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:latest ./app
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:latest

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Enable Helm OCI and Save Chart
        run: |
          helm registry login registry-1.docker.io \
            -u ${{ secrets.DOCKERHUB_USERNAME }} \
            -p ${{ secrets.DOCKERHUB_TOKEN }}

          helm package ./helm/hello-chart
          helm push hello-chart-0.1.0.tgz oci://registry-1.docker.io/${{ secrets.DOCKERHUB_USERNAME }}
