name: Publish Python App & Helm Chart

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: self-hosted
    #    outputs: # This section is commented out, so its indentation doesn't matter much,
    #      chart-version: ${{ steps.set-version.outputs.chart-version }} # but if uncommented, ensure it aligns with 'outputs:'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #      - name: Build and Push Docker Image to Docker Hub # This block was commented out, leaving it as is.
      #        run: |
      #          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:latest ./app
      #          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:latest

      - name: Build and Push Docker Image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:latest

      - name: Extract Chart Version
        id: chart
        run: |
          VERSION=$(grep '^version:' ./helm/hello-chart/Chart.yaml | cut -d ':' -f2 | xargs)
          echo "Chart version detected: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "$VERSION" > chart-version.txt # Added quotes around $VERSION for robustness

      # Store chart version to be used in other isolated workflow (i.e deploy)
      - name: Upload Chart Version Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chart-version
          path: chart-version.txt

      # Config Helm
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      # Imporatnt! Runs on Linux only (not macOs)
      # 1. Logs in to the OCI registry
      # 2. Runs helm package
      # 3. Runs helm push

      #      - name: Push Helm Chart to Docker Hub OCI # This block was commented out, leaving it as is.
      #        uses: bsord/helm-push@v4
      #        with:
      #          useOCI: true
      #          username: ${{ secrets.DOCKERHUB_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #          registry-url: oci://registry-1.docker.io/${{ secrets.DOCKERHUB_USERNAME }}
      #          chart-folder: ./helm/hello-chart

      # Note: awk grabs the generated .tgz filename (last word of the Helm output)
      - name: Package & Push Helm Chart to Docker Hub OCI (auto version)
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | helm registry login registry-1.docker.io \
            --username ${{ secrets.DOCKERHUB_USERNAME }} \
            --password-stdin

          CHART_DIR="./helm/hello-chart"
          CHART_PACKAGE=$(helm package "$CHART_DIR" --destination . | awk '{print $NF}')
          helm push "$CHART_PACKAGE" "oci://registry-1.docker.io/${{ secrets.DOCKERHUB_USERNAME }}" # Added quotes around OCI URL for robustness

  deploy:
    runs-on: self-hosted
    needs: build-and-publish

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Chart Version Artifact
          uses: actions/download-artifact@v4
          with:
            name: chart-version # This 'name' must match the 'name' used in your 'Upload Chart Version Artifact' step
            path: . # This will download the artifact to the current working directory, so 'cat chart-version.txt' can find it.

      - name: Prepare Application Manifest
        run: |
          CHART_VERSION=$(cat chart-version.txt)
          DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}

          sed -e "s|\${CHART_VERSION}|$CHART_VERSION|g" \
              -e "s|\${DOCKERHUB_USERNAME}|$DOCKERHUB_USERNAME|g" \
              argocd-apps/hello-chart-app.yaml.template > argocd-apps/hello-chart-app.yaml

      - name: Apply ArgoCD Application
        run: |
          kubectl apply -f argocd-apps/hello-chart-app.yaml

      # --- START Workaround: Establish Port-Forwarding Tunnel ---
      - name: Start ArgoCD Ingress Port Forward
        id: start_port_forward
        run: |
          NGINX_POD=$(kubectl get pods -n ingress-nginx -l app.kubernetes.io/name=nginx-ingress-controller -o jsonpath='{.items[0].metadata.name}')

          if [ -z "$NGINX_POD" ]; then
            echo "Error: NGINX Ingress Controller pod not found. Exiting."
            exit 1
          fi

          echo "Found NGINX Ingress Controller Pod: $NGINX_POD"

          # Start port-forwarding in background
          kubectl port-forward -n ingress-nginx "$NGINX_POD" 8443:443 &
          PF_PID=$!
          echo "Port-forwarding started for NGINX Ingress Controller on localhost:8443 (PID: $PF_PID)"
          echo "PF_PID=$PF_PID" >> "$GITHUB_ENV"

          # --- Robust Wait Loop for Port-Forwarding ---
          echo "Waiting for port-forwarding tunnel to be ready..."
          timeout=60 # Max wait time in seconds
          elapsed=0
          while ! nc -z localhost 8443 >/dev/null 2>&1; do
            if [ $elapsed -ge $timeout ]; then
              echo "Error: Port-forwarding tunnel did not become ready within $timeout seconds."
              kill "$PF_PID" || true # Try to kill if it's still running
              exit 1
            fi
            echo "Port 8443 not yet open. Waiting..."
            sleep 5
            elapsed=$((elapsed + 5))
          done
          echo "Port-forwarding tunnel established and ready."
        timeout-minutes: 2 # Increase timeout for this step to accommodate the wait loop

      # --- Use the Tunnel for Argo CD Commands ---
      - name: Login to Argo CD via Port Forward
        run: |
          yes | argocd login localhost:8443 \
            --insecure --grpc-web \
            --auth-token ${{ secrets.ARGOCD_TOKEN }}

      - name: Sync Application via Port Forward
        run: argocd app sync hello-chart-app --grpc-web

      - name: Wait for Health via Port Forward
        run: argocd app wait hello-chart-app --health --operation --timeout 90s --grpc-web

      # --- END Workaround: Clean Up Port-Forwarding Tunnel ---
      - name: Stop ArgoCD Ingress Port Forward
        if: always()
        run: |
          if [ -n "$PF_PID" ]; then
            echo "Stopping port-forwarding process (PID: $PF_PID)..."
            # Use 'kill -0' to check if process exists before attempting to kill
            if kill -0 "$PF_PID" >/dev/null 2>&1; then
              kill "$PF_PID"
              echo "Port-forwarding stopped."
            else
              echo "Port-forwarding process (PID: $PF_PID) already terminated."
            fi
          else
            echo "No port-forwarding process PID found, skipping termination."
          fi